logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./test123
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

  # redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379


server:
  port: 8081


logging.level:
  org.hibernate.SQL: debug




jwt:
  secret-key: Asdw-aswdfg.vbngty_ssd_2343_secret_key
  # 30 days
  token.expired-time-ms: 2592000000

# ?? ??
#spring:
#  profiles:
#    default: local
#
#  datasource:
#    url: jdbc:h2:tcp://localhost/./test123
#    username: sa
#    password: 1234
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#
#---
#spring:
#  config:
#    activate:
#      on-profile: local
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show_sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        # data.sql ??
#    defer-datasource-initialization: true
#
#  h2:
#    console:
#      enabled: true
#
#logging.level:
#  org.hibernate.SQL: debug
#
#---
#spring:
#  config:
#    activate:
#      on-profile: test
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show_sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  #        use_sql_comments: true
#
#  # data.sql ?? X
#  sql:
#    init:
#      mode: never